package com.example.data.model

data class AiVisionResult(
    val id: String = java.util.UUID.randomUUID().toString(),
    val imageSource: String, // "CAMERA", "GALLERY", "SAMPLE_BENCHMARK"
    val sampleTitle: String? = null,
    val detectedCategory: String, // "Roads", "Sanitation", "Water", "Electricity", "Public Safety"
    val damageType: String, // e.g., "Deep Bitumen Pothole", "Municipal Garbage Dump Overspill"
    val severityScore: Int, // 1 - 100
    val severityLevel: String, // "CRITICAL", "HIGH", "MODERATE", "LOW"
    val confidenceScore: Float, // 0.0 - 1.0 (e.g. 0.96)
    val estimatedRepairCost: String, // e.g. "₹4,500 - ₹7,200"
    val recommendedSlaHours: Int, // e.g. 24, 48, 72
    val detectedObjects: List<String>, // e.g. ["Bitumen Crater (45cm)", "Edge Fractures", "Traffic Risk"]
    val publicSafetyImpact: String,
    val suggestedDepartment: String,
    val technicalAssessment: String,
    val autoGeneratedTitle: String,
    val autoGeneratedDescription: String
)

data class VisionSampleCase(
    val id: String,
    val title: String,
    val category: String,
    val imageResName: String,
    val description: String,
    val benchmarkSource: String, // e.g. "Smart Cities Mission / MoHUA Civic AI Benchmark"
    val defaultResult: AiVisionResult
)
